version: "3"
services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    environment:
      - REACT_APP_NAME=docker_example
      - CHOKIDAR_USEPOLLING=true